FROM python:3.11-alpine as BUILD

WORKDIR /app

COPY requirements.txt /app/
RUN apk update && apk add python3-dev \
                        gcc \
                        libc-dev \
                        linux-headers 

RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-alpine as PROD

COPY --from=BUILD  /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=BUILD /usr/local/bin /usr/local/bin

WORKDIR /app/

COPY . /app/

EXPOSE ${PORT}

ENTRYPOINT ["python"]