
version: "3"

services:
  warehouse:
    container_name: "warehouse"
    ports:
     - "8082:8082"
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Containerfile
    environment:
      - PORT=8082
    networks:
      - warehouse-network

networks:
  warehouse-network: