version: "3"

services:

  
  node:
    build: 
      context: ./warehouse
      dockerfile: Containerfile
    command: server.py
    networks:
      - warehouse-network
    deploy:
      replicas: 1

  client:
    build: 
      context: ./warehouse
      dockerfile: Containerfile
    command: client.py
    ports:
     - "8082:8082"
    networks:
      - warehouse-network
    deploy:
      replicas: 1

networks:
  warehouse-network: