version: "3"

services:

  
  node:
    build: 
      context: ./warehouse
      dockerfile: Containerfile
    command: server.py
    ports:
      - 10000:10000
      - 12345:12345
      - 12346:12346
      - 12347:12347
      - 64000:64000
    networks:
      - warehouse-network
    deploy:
      replicas: 1

  client:
    build: 
      context: ./warehouse
      dockerfile: Containerfile
    command: client.py
    ports:
     - "8082:8082"
    networks:
      - warehouse-network
    deploy:
      replicas: 1

networks:
  warehouse-network: