version: "3"

services:
#  leader:
#    hostname: leader
#    build: 
#      context: ./warehouse
#      dockerfile: Containerfile
#    command: reliableMulticast/reliableMulticast.py leader
#    command: server.py
#    networks:
#      - warehouse-network
#    stdin_open: true # docker run -i
#    tty: true  
#    deploy:
#      replicas: 1
  
  node:
    build: 
      context: ./warehouse
      dockerfile: Containerfile
#    command: test.py
    command: server.py
    networks:
      - warehouse-network
    stdin_open: true # docker run -i
    tty: true  
    deploy:
      replicas: 2

  client:
    build: 
      context: ./warehouse
      dockerfile: Containerfile
    command: client.py
    ports:
     - "8082:8082"
    networks:
      - warehouse-network
    deploy:
      replicas: 0

networks:
  warehouse-network: