# Generated by Django 5.0.1 on 2024-01-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeinModell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('inhalt', models.TextField()),
                ('erstelldatum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
